// All datasets — add new cities/categories here
// Each entry: { label, city, category, businesses: [...] }

const DATASETS = {

  /* ── Austin · Plumbers ─────────────────────────────────────── */
  'austin-plumbers': {
    label: 'Plumbers',
    city: 'Austin, TX',
    category: 'Plumbers',
    sampleData: false,
    businesses: [
      {
        id: 1,
        name: "Radiant Plumbing & Air Conditioning",
        address: "901 Reinli St, Austin, TX 78751",
        googleRating: 4.8, reviewCount: 12426, recentReviewPct: 0.18,
        packPosition: 1, keywordRankAvg: 1.5,
        pageSpeed: 72, auditScore: 75, mobileScore: 68,
        websiteUrl: "https://radiantplumbing.com",
        dataSource: "ThreeBestRated #1 · Birdeye 12,426 reviews",
        dataSourceUrl: "https://threebestrated.com",
      },
      {
        id: 2,
        name: "Rooter-Man Plumbing Austin",
        address: "15503 Patricia St, Austin, TX 78728",
        googleRating: 4.9, reviewCount: 705, recentReviewPct: 0.45,
        packPosition: 2, keywordRankAvg: 3.2,
        pageSpeed: 52, auditScore: 58, mobileScore: 50,
        websiteUrl: "https://www.rooterman.com/greater-austin/",
        dataSource: "TrustAnalytica · Birdeye 1,202 cross-platform",
        dataSourceUrl: "https://trustanalytica.com",
      },
      {
        id: 3,
        name: "Reliant Plumbing",
        address: "8740 N Lamar Blvd #203A, Austin, TX 78753",
        googleRating: 4.9, reviewCount: 784, recentReviewPct: 0.48,
        packPosition: 3, keywordRankAvg: 4.8,
        pageSpeed: 68, auditScore: 72, mobileScore: 65,
        websiteUrl: "https://reliantplumbing.com",
        dataSource: "ThreeBestRated #3 · TrustAnalytica 784 reviews",
        dataSourceUrl: "https://threebestrated.com",
      },
      {
        id: 4,
        name: "Proven Plumbing & Air",
        address: "300 Brushy Creek Rd Ste 402, Cedar Park, TX 78613",
        googleRating: 4.9, reviewCount: 2798, recentReviewPct: 0.40,
        packPosition: 4, keywordRankAvg: 7.1,
        pageSpeed: 71, auditScore: 74, mobileScore: 70,
        websiteUrl: "https://www.callproven.com",
        dataSource: "ServiceAgent · Birdeye 2,798 Google reviews",
        dataSourceUrl: "https://www.serviceagent.com",
      },

      {
        id: 5,
        name: "ABC Home & Commercial Services",
        address: "9475 US-290, Austin, TX 78724",
        googleRating: 4.9, reviewCount: 979, recentReviewPct: 0.30,
        packPosition: 5, keywordRankAvg: 8.5,
        pageSpeed: 65, auditScore: 68, mobileScore: 60,
        websiteUrl: "https://www.abchomeandcommercial.com/austin/plumbing",
        dataSource: "ConsumerAffairs · Birdeye 1,128 reviews · est. 1949",
        dataSourceUrl: "https://www.consumeraffairs.com",
      },
      {
        id: 6,
        name: "Daniel's Plumbing and Air Conditioning",
        address: "2929 Longhorn Blvd #105, Austin, TX 78758",
        googleRating: 4.7, reviewCount: 2772, recentReviewPct: 0.42,
        packPosition: 6, keywordRankAvg: 10.2,
        pageSpeed: 74, auditScore: 76, mobileScore: 72,
        websiteUrl: "https://www.danielsaustin.com",
        dataSource: "ServiceAgent · Homespothq 2,772 Google reviews",
        dataSourceUrl: "https://www.serviceagent.com",
      },
      {
        id: 7,
        name: "Fox Service Company",
        address: "1506 Ferguson Ln Ste 102, Austin, TX 78754",
        googleRating: 4.8, reviewCount: 5127, recentReviewPct: 0.22,
        packPosition: 7, keywordRankAvg: 11.8,
        pageSpeed: 63, auditScore: 66, mobileScore: 59,
        websiteUrl: "https://www.foxservice.com",
        dataSource: "Birdeye 6,094 cross-platform · est. 1972",
        dataSourceUrl: "https://birdeye.com",
      },
      {
        id: 8,
        name: "Stan's Heating, Air, Plumbing & Electrical",
        address: "6016 Dillard Cir, Austin, TX 78752",
        googleRating: 4.7, reviewCount: 6791, recentReviewPct: 0.20,
        packPosition: 8, keywordRankAvg: 13.2,
        pageSpeed: 58, auditScore: 61, mobileScore: 55,
        websiteUrl: "https://www.stansac.com",
        dataSource: "Birdeye 6,791 Google · 573 Yelp · est. 1954",
        dataSourceUrl: "https://birdeye.com",
      },

      {
        id: 9,
        name: "Abacus Plumbing, AC & Electrical",
        address: "2106 Denton Dr, Austin, TX 78758",
        googleRating: 4.6, reviewCount: 578, recentReviewPct: 0.35,
        packPosition: 9, keywordRankAvg: 15.5,
        pageSpeed: 66, auditScore: 70, mobileScore: 64,
        websiteUrl: "https://www.abacusplumbing.com",
        dataSource: "Best Pick Reports 4.6★ · 578 Google reviews · est. 2003",
        dataSourceUrl: "https://bestpickreports.com",
      },
      {
        id: 10,
        name: "S&D Plumbing",
        address: "3432 Greystone Dr Ste 112, Austin, TX 78731",
        googleRating: 4.7, reviewCount: 816, recentReviewPct: 0.38,
        packPosition: 10, keywordRankAvg: 17.3,
        pageSpeed: 61, auditScore: 64, mobileScore: 58,
        websiteUrl: "https://www.sanddplumbing.com",
        dataSource: "Birdeye 816 Google · family-owned est. 1980",
        dataSourceUrl: "https://birdeye.com",
      },
      {
        id: 11,
        name: "Moore & More Plumbing",
        address: "1816 Bissel Ln, Austin, TX 78745",
        googleRating: 4.8, reviewCount: 266, recentReviewPct: 0.50,
        packPosition: 11, keywordRankAvg: 19.0,
        pageSpeed: 55, auditScore: 52, mobileScore: 50,
        websiteUrl: "https://www.mooremoreplumbing.com",
        dataSource: "Birdeye 338 cross-platform · est. 1986",
        dataSourceUrl: "https://birdeye.com",
      },
      {
        id: 12,
        name: "EZ Flow Plumbing",
        address: "1914 W Howard Ln Ste J, Austin, TX 78728",
        googleRating: 4.9, reviewCount: 54, recentReviewPct: 0.65,
        packPosition: 12, keywordRankAvg: 22.0,
        pageSpeed: 48, auditScore: 44, mobileScore: 45,
        websiteUrl: "https://ezflowplumbingtexas.com",
        dataSource: "4.9★ Google · 276 Yelp reviews · est. 2009",
        dataSourceUrl: "https://www.yelp.com",
      },

      {
        id: 13,
        name: "Excalibur Plumbing",
        address: "11880 Hero Way W Ste 308, Leander, TX 78641",
        googleRating: 4.7, reviewCount: 501, recentReviewPct: 0.40,
        packPosition: 13, keywordRankAvg: 23.5,
        pageSpeed: 70, auditScore: 72, mobileScore: 68,
        websiteUrl: "https://www.excaliburplumbing.com",
        dataSource: "Birdeye 501 Google · Angi 92% approval",
        dataSourceUrl: "https://birdeye.com",
      },
      {
        id: 14,
        name: "Economy Plumbing Services",
        address: "701 Tillery St Ste 12, Austin, TX 78702",
        googleRating: 4.6, reviewCount: 586, recentReviewPct: 0.35,
        packPosition: 14, keywordRankAvg: 25.0,
        pageSpeed: 52, auditScore: 48, mobileScore: 50,
        websiteUrl: "https://www.plumbersthatcare.com",
        dataSource: "ServiceAgent 586 Google · Birdeye 642 reviews · est. 2012",
        dataSourceUrl: "https://www.serviceagent.com",
      },
      {
        id: 15,
        name: "Roto-Rooter Plumbing & Water Cleanup",
        address: "2324 Ridgepoint Dr Ste A, Austin, TX 78754",
        googleRating: 4.6, reviewCount: 400, recentReviewPct: 0.30,
        packPosition: 15, keywordRankAvg: 26.5,
        pageSpeed: 60, auditScore: 62, mobileScore: 58,
        websiteUrl: "https://www.rotorooter.com/austin/",
        dataSource: "ThreeBestRated top-3 · TrustAnalytica 4.6★ · 302 Yelp",
        dataSourceUrl: "https://threebestrated.com",
      },
      {
        id: 16,
        name: "Redbud Plumbing",
        address: "9705 Burnet Rd Ste 605, Austin, TX 78758",
        googleRating: 4.9, reviewCount: 75, recentReviewPct: 0.70,
        packPosition: 16, keywordRankAvg: 28.0,
        pageSpeed: 72, auditScore: 68, mobileScore: 70,
        websiteUrl: "https://redbudplumbing.com",
        dataSource: "Angi 5.0★ · BuildZoom top 11% TX contractors",
        dataSourceUrl: "https://www.angi.com",
      },

      {
        id: 17,
        name: "Clarke Kent Plumbing",
        address: "1408 W Ben White Blvd, Austin, TX 78704",
        googleRating: 4.4, reviewCount: 485, recentReviewPct: 0.28,
        packPosition: 17, keywordRankAvg: 29.5,
        pageSpeed: 45, auditScore: 41, mobileScore: 43,
        websiteUrl: "https://www.clarkekentplumbing.com",
        dataSource: "TrustAnalytica 4.4★ · 210 Yelp reviews · est. 1986",
        dataSourceUrl: "https://trustanalytica.com",
      },
      {
        id: 18,
        name: "Wilson Plumbing Company",
        address: "906 E 47th St, Austin, TX 78751",
        googleRating: 4.8, reviewCount: 40, recentReviewPct: 0.40,
        packPosition: 18, keywordRankAvg: 31.0,
        pageSpeed: 38, auditScore: 35, mobileScore: 36,
        websiteUrl: "https://www.wilsonplumbingaustin.com",
        dataSource: "Angi 4.9★ · Super Service Awards 2011–2017 · est. 1947",
        dataSourceUrl: "https://www.angi.com",
      },
      {
        id: 19,
        name: "Accurate Plumbing Solutions",
        address: "5234 Balcones Dr, Austin, TX 78731",
        googleRating: 4.8, reviewCount: 342, recentReviewPct: 0.52,
        packPosition: 19, keywordRankAvg: 32.0,
        pageSpeed: 55, auditScore: 58, mobileScore: 52,
        websiteUrl: "https://www.accurateplumbingaustin.com",
        dataSource: "Sample data — BestProsInTown featured · est. 2010",
        dataSourceUrl: "https://bestprosintown.com",
      },
      {
        id: 20,
        name: "Altruistic Plumbing",
        address: "7800 Shoal Creek Blvd Ste 265, Austin, TX 78757",
        googleRating: 4.9, reviewCount: 189, recentReviewPct: 0.62,
        packPosition: 20, keywordRankAvg: 33.5,
        pageSpeed: 60, auditScore: 55, mobileScore: 57,
        websiteUrl: "https://www.altruisticplumbing.com",
        dataSource: "Sample data — Thumbtack top pro · est. 2017",
        dataSourceUrl: "https://www.thumbtack.com",
      },

      {
        id: 21,
        name: "Blue Dragon Plumbing",
        address: "5555 N Lamar Blvd Ste C107, Austin, TX 78751",
        googleRating: 4.8, reviewCount: 312, recentReviewPct: 0.55,
        packPosition: 21, keywordRankAvg: 34.5,
        pageSpeed: 58, auditScore: 54, mobileScore: 56,
        websiteUrl: "https://www.bluedragonplumbing.com",
        dataSource: "Sample data — Angi highly rated · est. 2015",
        dataSourceUrl: "https://www.angi.com",
      },
      {
        id: 22,
        name: "Thunderbird Plumbing",
        address: "12233 Ranch Rd 620 N, Austin, TX 78750",
        googleRating: 4.7, reviewCount: 428, recentReviewPct: 0.44,
        packPosition: 22, keywordRankAvg: 35.5,
        pageSpeed: 62, auditScore: 60, mobileScore: 58,
        websiteUrl: "https://www.thunderbirdplumbingatx.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 23,
        name: "Hill Country Plumbing Co.",
        address: "3300 Bee Cave Rd Ste 650, Austin, TX 78746",
        googleRating: 4.9, reviewCount: 274, recentReviewPct: 0.58,
        packPosition: 23, keywordRankAvg: 36.5,
        pageSpeed: 66, auditScore: 63, mobileScore: 62,
        websiteUrl: "https://www.hillcountryplumbingco.com",
        dataSource: "Sample data — Expertise.com featured · est. 2013",
        dataSourceUrl: "https://www.expertise.com",
      },
      {
        id: 24,
        name: "Capital Plumbing Solutions",
        address: "1701 Directors Blvd Ste 300, Austin, TX 78744",
        googleRating: 4.6, reviewCount: 356, recentReviewPct: 0.40,
        packPosition: 24, keywordRankAvg: 37.5,
        pageSpeed: 54, auditScore: 50, mobileScore: 51,
        websiteUrl: "https://www.capitalplumbingsolutions.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 25,
        name: "Barton Springs Plumbing",
        address: "2422 S Lamar Blvd, Austin, TX 78704",
        googleRating: 4.8, reviewCount: 645, recentReviewPct: 0.47,
        packPosition: 25, keywordRankAvg: 38.5,
        pageSpeed: 64, auditScore: 61, mobileScore: 60,
        websiteUrl: "https://www.bartonspringsplumbing.com",
        dataSource: "Sample data — local favorite · est. 2008",
      },
      {
        id: 26,
        name: "Longhorn Plumbing & Drain",
        address: "9200 Cameron Rd Ste 200, Austin, TX 78754",
        googleRating: 4.5, reviewCount: 512, recentReviewPct: 0.33,
        packPosition: 26, keywordRankAvg: 39.5,
        pageSpeed: 50, auditScore: 46, mobileScore: 48,
        websiteUrl: "https://www.longhornplumbingdrain.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 27,
        name: "ATX Pipe & Sewer",
        address: "6800 Burnet Rd Ste 4, Austin, TX 78757",
        googleRating: 4.9, reviewCount: 198, recentReviewPct: 0.61,
        packPosition: 27, keywordRankAvg: 40.5,
        pageSpeed: 68, auditScore: 65, mobileScore: 64,
        websiteUrl: "https://www.atxpipeandsewer.com",
        dataSource: "Sample data — Thumbtack top pro · est. 2018",
        dataSourceUrl: "https://www.thumbtack.com",
      },
      {
        id: 28,
        name: "Violet Crown Plumbing",
        address: "1100 S Congress Ave, Austin, TX 78704",
        googleRating: 4.7, reviewCount: 289, recentReviewPct: 0.49,
        packPosition: 28, keywordRankAvg: 41.5,
        pageSpeed: 56, auditScore: 53, mobileScore: 54,
        websiteUrl: "https://www.violetcrownplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 29,
        name: "Guadalupe Plumbing Services",
        address: "4315 Guadalupe St, Austin, TX 78751",
        googleRating: 4.6, reviewCount: 421, recentReviewPct: 0.36,
        packPosition: 29, keywordRankAvg: 42.5,
        pageSpeed: 52, auditScore: 49, mobileScore: 50,
        websiteUrl: "https://www.guadalupeplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 30,
        name: "Zilker Plumbing Group",
        address: "2001 Barton Springs Rd, Austin, TX 78704",
        googleRating: 4.8, reviewCount: 367, recentReviewPct: 0.53,
        packPosition: 30, keywordRankAvg: 43.5,
        pageSpeed: 60, auditScore: 57, mobileScore: 56,
        websiteUrl: "https://www.zilkerplumbinggroup.com",
        dataSource: "Sample data — HomeAdvisor featured · est. 2014",
        dataSourceUrl: "https://www.homeadvisor.com",
      },
      {
        id: 31,
        name: "Mueller District Plumbing",
        address: "1900 Aldrich St Ste 130, Austin, TX 78723",
        googleRating: 4.7, reviewCount: 233, recentReviewPct: 0.51,
        packPosition: 31, keywordRankAvg: 44.5,
        pageSpeed: 63, auditScore: 60, mobileScore: 59,
        websiteUrl: "https://www.muellerdistrictplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 32,
        name: "Pecan Street Plumbing",
        address: "300 E 6th St, Austin, TX 78701",
        googleRating: 4.5, reviewCount: 178, recentReviewPct: 0.42,
        packPosition: 32, keywordRankAvg: 45.5,
        pageSpeed: 48, auditScore: 44, mobileScore: 45,
        websiteUrl: "https://www.pecanstreetplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 33,
        name: "Colorado River Plumbing",
        address: "5900 W Slaughter Ln Ste C, Austin, TX 78749",
        googleRating: 4.9, reviewCount: 302, recentReviewPct: 0.57,
        packPosition: 33, keywordRankAvg: 46.5,
        pageSpeed: 65, auditScore: 62, mobileScore: 61,
        websiteUrl: "https://www.coloradoriverplumbing.com",
        dataSource: "Sample data — Angi Super Service · est. 2011",
        dataSourceUrl: "https://www.angi.com",
      },
      {
        id: 34,
        name: "Lady Bird Plumbing",
        address: "600 River St, Austin, TX 78701",
        googleRating: 4.6, reviewCount: 254, recentReviewPct: 0.39,
        packPosition: 34, keywordRankAvg: 47.5,
        pageSpeed: 54, auditScore: 51, mobileScore: 52,
        websiteUrl: "https://www.ladybirdplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 35,
        name: "Congress Avenue Plumbing",
        address: "1010 Congress Ave Ste 200, Austin, TX 78701",
        googleRating: 4.7, reviewCount: 411, recentReviewPct: 0.45,
        packPosition: 35, keywordRankAvg: 48.5,
        pageSpeed: 59, auditScore: 56, mobileScore: 55,
        websiteUrl: "https://www.congressavenueplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 36,
        name: "Balcones Plumbing & Rooter",
        address: "8127 Mesa Dr Ste B206, Austin, TX 78759",
        googleRating: 4.8, reviewCount: 523, recentReviewPct: 0.48,
        packPosition: 36, keywordRankAvg: 49.5,
        pageSpeed: 61, auditScore: 58, mobileScore: 57,
        websiteUrl: "https://www.balconesplumbing.com",
        dataSource: "Sample data — Birdeye 523 Google · est. 2009",
        dataSourceUrl: "https://birdeye.com",
      },
      {
        id: 37,
        name: "Onion Creek Plumbing",
        address: "9600 S IH-35 Frontage Rd, Austin, TX 78748",
        googleRating: 4.5, reviewCount: 187, recentReviewPct: 0.34,
        packPosition: 37, keywordRankAvg: 50.5,
        pageSpeed: 46, auditScore: 43, mobileScore: 44,
        websiteUrl: "https://www.onioncreekplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 38,
        name: "Shoal Creek Plumbing",
        address: "3701 Guadalupe St Ste 200, Austin, TX 78705",
        googleRating: 4.9, reviewCount: 341, recentReviewPct: 0.56,
        packPosition: 38, keywordRankAvg: 51.5,
        pageSpeed: 67, auditScore: 64, mobileScore: 63,
        websiteUrl: "https://www.shoalcreekplumbing.com",
        dataSource: "Sample data — Expertise.com featured · est. 2012",
        dataSourceUrl: "https://www.expertise.com",
      },
      {
        id: 39,
        name: "Travis County Plumbing",
        address: "5524 Bee Caves Rd Ste B5, Austin, TX 78746",
        googleRating: 4.6, reviewCount: 276, recentReviewPct: 0.41,
        packPosition: 39, keywordRankAvg: 52.5,
        pageSpeed: 53, auditScore: 50, mobileScore: 51,
        websiteUrl: "https://www.traviscountyplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 40,
        name: "South Lamar Plumbing",
        address: "3800 S Lamar Blvd Ste 250, Austin, TX 78704",
        googleRating: 4.7, reviewCount: 198, recentReviewPct: 0.50,
        packPosition: 40, keywordRankAvg: 53.5,
        pageSpeed: 57, auditScore: 54, mobileScore: 53,
        websiteUrl: "https://www.southlamarplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 41,
        name: "Domain Plumbing Pros",
        address: "11701 Domain Blvd Ste 3, Austin, TX 78758",
        googleRating: 4.8, reviewCount: 289, recentReviewPct: 0.54,
        packPosition: 41, keywordRankAvg: 54.5,
        pageSpeed: 62, auditScore: 59, mobileScore: 58,
        websiteUrl: "https://www.domainplumbingpros.com",
        dataSource: "Sample data — HomeAdvisor featured · est. 2016",
        dataSourceUrl: "https://www.homeadvisor.com",
      },
      {
        id: 42,
        name: "Manor Road Plumbing",
        address: "1700 Manor Rd, Austin, TX 78722",
        googleRating: 4.5, reviewCount: 145, recentReviewPct: 0.37,
        packPosition: 42, keywordRankAvg: 55.5,
        pageSpeed: 44, auditScore: 41, mobileScore: 42,
        websiteUrl: "https://www.manorroadplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 43,
        name: "Slaughter Lane Plumbing",
        address: "1201 W Slaughter Ln, Austin, TX 78748",
        googleRating: 4.6, reviewCount: 312, recentReviewPct: 0.43,
        packPosition: 43, keywordRankAvg: 56.5,
        pageSpeed: 51, auditScore: 48, mobileScore: 49,
        websiteUrl: "https://www.slaughterlaneplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 44,
        name: "Anderson Mill Plumbing",
        address: "13343 US-183 Hwy Ste 100, Austin, TX 78750",
        googleRating: 4.8, reviewCount: 401, recentReviewPct: 0.46,
        packPosition: 44, keywordRankAvg: 57.5,
        pageSpeed: 60, auditScore: 57, mobileScore: 56,
        websiteUrl: "https://www.andersonmillplumbing.com",
        dataSource: "Sample data — Birdeye 401 Google · est. 2010",
        dataSourceUrl: "https://birdeye.com",
      },
      {
        id: 45,
        name: "Del Valle Plumbing",
        address: "3800 FM 973, Del Valle, TX 78617",
        googleRating: 4.5, reviewCount: 167, recentReviewPct: 0.35,
        packPosition: 45, keywordRankAvg: 58.5,
        pageSpeed: 47, auditScore: 44, mobileScore: 45,
        websiteUrl: "https://www.delvalleplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 46,
        name: "Pflugerville Plumbing Experts",
        address: "1600 Grand Ave Pkwy Ste 100, Pflugerville, TX 78660",
        googleRating: 4.9, reviewCount: 358, recentReviewPct: 0.59,
        packPosition: 46, keywordRankAvg: 59.5,
        pageSpeed: 66, auditScore: 63, mobileScore: 62,
        websiteUrl: "https://www.pflugervilleplumbingexperts.com",
        dataSource: "Sample data — Angi Super Service · est. 2013",
        dataSourceUrl: "https://www.angi.com",
      },
      {
        id: 47,
        name: "Round Rock Plumbing Co.",
        address: "2000 S Mays St Ste 200, Round Rock, TX 78664",
        googleRating: 4.6, reviewCount: 298, recentReviewPct: 0.40,
        packPosition: 47, keywordRankAvg: 60.5,
        pageSpeed: 55, auditScore: 52, mobileScore: 53,
        websiteUrl: "https://www.roundrockplumbingco.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 48,
        name: "Cedar Park Plumbing Services",
        address: "1335 E Whitestone Blvd Ste K, Cedar Park, TX 78613",
        googleRating: 4.7, reviewCount: 445, recentReviewPct: 0.44,
        packPosition: 48, keywordRankAvg: 61.5,
        pageSpeed: 58, auditScore: 55, mobileScore: 54,
        websiteUrl: "https://www.cedarparkplumbingservices.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 49,
        name: "Leander Plumbing & Rooter",
        address: "651 N US-183 Hwy Ste 100, Leander, TX 78641",
        googleRating: 4.8, reviewCount: 213, recentReviewPct: 0.52,
        packPosition: 49, keywordRankAvg: 62.5,
        pageSpeed: 61, auditScore: 58, mobileScore: 57,
        websiteUrl: "https://www.leanderplumbingrooter.com",
        dataSource: "Sample data — HomeAdvisor featured · est. 2017",
        dataSourceUrl: "https://www.homeadvisor.com",
      },
      {
        id: 50,
        name: "Buda Plumbing Pros",
        address: "500 Main St Ste 200, Buda, TX 78610",
        googleRating: 4.5, reviewCount: 132, recentReviewPct: 0.38,
        packPosition: 50, keywordRankAvg: 63.5,
        pageSpeed: 45, auditScore: 42, mobileScore: 43,
        websiteUrl: "https://www.budaplumbingpros.com",
        dataSource: "Sample data — pending live pull",
      },
    ],
  },


  /* ── Austin · HVAC ─────────────────────────────────────────── */
  'austin-hvac': {
    label: 'HVAC & AC Repair',
    city: 'Austin, TX',
    category: 'HVAC & AC Repair',
    businesses: [
      {
        id: 1,
        name: "Strand Brothers Service Experts",
        address: "4800 E Ben White Blvd, Austin, TX 78741",
        googleRating: 4.7, reviewCount: 3241, recentReviewPct: 0.35,
        packPosition: 1, keywordRankAvg: 2.1,
        pageSpeed: 70, auditScore: 72, mobileScore: 68,
        websiteUrl: "https://www.strandbrothers.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 2,
        name: "Fox Service Company",
        address: "1506 Ferguson Ln Ste 102, Austin, TX 78754",
        googleRating: 4.8, reviewCount: 5127, recentReviewPct: 0.22,
        packPosition: 2, keywordRankAvg: 3.5,
        pageSpeed: 63, auditScore: 66, mobileScore: 59,
        websiteUrl: "https://www.foxservice.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 3,
        name: "Comfort Systems USA",
        address: "7700 Chevy Chase Dr, Austin, TX 78752",
        googleRating: 4.6, reviewCount: 1892, recentReviewPct: 0.30,
        packPosition: 3, keywordRankAvg: 5.0,
        pageSpeed: 68, auditScore: 70, mobileScore: 65,
        websiteUrl: "https://www.comfortsystemsusa.com",
        dataSource: "Sample data — pending live pull",
      },

      {
        id: 4,
        name: "Stan's Heating, Air, Plumbing & Electrical",
        address: "6016 Dillard Cir, Austin, TX 78752",
        googleRating: 4.7, reviewCount: 6791, recentReviewPct: 0.20,
        packPosition: 4, keywordRankAvg: 7.2,
        pageSpeed: 58, auditScore: 61, mobileScore: 55,
        websiteUrl: "https://www.stansac.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 5,
        name: "One Hour Air Conditioning & Heating",
        address: "9430 Research Blvd Ste 400, Austin, TX 78759",
        googleRating: 4.5, reviewCount: 1124, recentReviewPct: 0.38,
        packPosition: 5, keywordRankAvg: 9.5,
        pageSpeed: 74, auditScore: 76, mobileScore: 72,
        websiteUrl: "https://www.onehourhvac.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 6,
        name: "Daniel's Plumbing and Air Conditioning",
        address: "2929 Longhorn Blvd #105, Austin, TX 78758",
        googleRating: 4.7, reviewCount: 2772, recentReviewPct: 0.42,
        packPosition: 6, keywordRankAvg: 11.0,
        pageSpeed: 74, auditScore: 76, mobileScore: 72,
        websiteUrl: "https://www.danielsaustin.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 7,
        name: "Capital City AC & Heating",
        address: "5501 N Lamar Blvd, Austin, TX 78751",
        googleRating: 4.8, reviewCount: 432, recentReviewPct: 0.52,
        packPosition: 7, keywordRankAvg: 13.4,
        pageSpeed: 55, auditScore: 50, mobileScore: 52,
        websiteUrl: "https://www.capitalcityac.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 8,
        name: "Abacus Plumbing, AC & Electrical",
        address: "2106 Denton Dr, Austin, TX 78758",
        googleRating: 4.6, reviewCount: 578, recentReviewPct: 0.35,
        packPosition: 8, keywordRankAvg: 15.6,
        pageSpeed: 66, auditScore: 70, mobileScore: 64,
        websiteUrl: "https://www.abacusplumbing.com",
        dataSource: "Sample data — pending live pull",
      },

      {
        id: 9,
        name: "Radiant Plumbing & Air Conditioning",
        address: "901 Reinli St, Austin, TX 78751",
        googleRating: 4.8, reviewCount: 12426, recentReviewPct: 0.18,
        packPosition: 9, keywordRankAvg: 16.5,
        pageSpeed: 72, auditScore: 75, mobileScore: 68,
        websiteUrl: "https://radiantplumbing.com",
        dataSource: "Sample data — Birdeye 18,754 cross-platform reviews",
        dataSourceUrl: "https://birdeye.com",
      },
      {
        id: 10,
        name: "Blue Ribbon Cooling & Heating",
        address: "1000 Heritage Center Cir, Round Rock, TX 78664",
        googleRating: 4.9, reviewCount: 2105, recentReviewPct: 0.48,
        packPosition: 10, keywordRankAvg: 18.0,
        pageSpeed: 62, auditScore: 58, mobileScore: 60,
        websiteUrl: "https://www.blueribbonair.com",
        dataSource: "Sample data — Angi 5.0★ · Orbital top-9 by reviews",
        dataSourceUrl: "https://www.angi.com",
      },
      {
        id: 11,
        name: "ARS / Rescue Rooter Austin",
        address: "4606 S Lamar Blvd, Austin, TX 78745",
        googleRating: 4.5, reviewCount: 1845, recentReviewPct: 0.32,
        packPosition: 11, keywordRankAvg: 19.5,
        pageSpeed: 70, auditScore: 68, mobileScore: 66,
        websiteUrl: "https://www.ars.com/austin",
        dataSource: "Sample data — BBB accredited · Expertise.com featured",
        dataSourceUrl: "https://www.bbb.org",
      },
      {
        id: 12,
        name: "The Coolest LLC",
        address: "3601 S Congress Ave Ste C200, Austin, TX 78704",
        googleRating: 4.7, reviewCount: 380, recentReviewPct: 0.55,
        packPosition: 12, keywordRankAvg: 21.0,
        pageSpeed: 52, auditScore: 48, mobileScore: 50,
        websiteUrl: "https://www.thecoolestaustin.com",
        dataSource: "Sample data — BBB A+ · Expertise.com featured",
        dataSourceUrl: "https://www.bbb.org",
      },

      {
        id: 13,
        name: "Schneider Mechanical",
        address: "4900 W Howard Ln Ste 100, Austin, TX 78728",
        googleRating: 4.8, reviewCount: 621, recentReviewPct: 0.44,
        packPosition: 13, keywordRankAvg: 22.5,
        pageSpeed: 58, auditScore: 55, mobileScore: 54,
        websiteUrl: "https://www.schneidermechanical.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 14,
        name: "Airtron Austin",
        address: "2832 E Thompson Ln, Austin, TX 78742",
        googleRating: 4.6, reviewCount: 965, recentReviewPct: 0.30,
        packPosition: 14, keywordRankAvg: 24.0,
        pageSpeed: 64, auditScore: 62, mobileScore: 60,
        websiteUrl: "https://www.airtronaustin.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 15,
        name: "Trusted Heating & Cooling",
        address: "8868 Research Blvd Ste 500, Austin, TX 78758",
        googleRating: 4.9, reviewCount: 245, recentReviewPct: 0.60,
        packPosition: 15, keywordRankAvg: 25.5,
        pageSpeed: 50, auditScore: 46, mobileScore: 48,
        websiteUrl: "https://www.trustedheatingcooling.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 16,
        name: "Lex Air Conditioning & Heating",
        address: "3100 Alvin DeVane Blvd, Austin, TX 78741",
        googleRating: 4.7, reviewCount: 512, recentReviewPct: 0.40,
        packPosition: 16, keywordRankAvg: 27.0,
        pageSpeed: 68, auditScore: 65, mobileScore: 63,
        websiteUrl: "https://www.lexairconditioning.com",
        dataSource: "Sample data — pending live pull",
      },

      {
        id: 17,
        name: "Superior Attic & Air",
        address: "7200 N Lamar Blvd Ste 102, Austin, TX 78752",
        googleRating: 4.8, reviewCount: 310, recentReviewPct: 0.58,
        packPosition: 17, keywordRankAvg: 28.5,
        pageSpeed: 45, auditScore: 42, mobileScore: 44,
        websiteUrl: "https://www.superioratticandair.com",
        dataSource: "Sample data — Angi highly rated · spray foam specialist",
        dataSourceUrl: "https://www.angi.com",
      },
      {
        id: 18,
        name: "All Year Heating & Cooling",
        address: "12129 RR 620 N Ste 401, Austin, TX 78750",
        googleRating: 4.6, reviewCount: 198, recentReviewPct: 0.42,
        packPosition: 18, keywordRankAvg: 30.0,
        pageSpeed: 56, auditScore: 52, mobileScore: 53,
        websiteUrl: "https://www.allyearaustin.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 19,
        name: "Precision Heating & Air",
        address: "5301 Manchaca Rd Ste 200, Austin, TX 78745",
        googleRating: 4.7, reviewCount: 275, recentReviewPct: 0.45,
        packPosition: 19, keywordRankAvg: 31.5,
        pageSpeed: 60, auditScore: 57, mobileScore: 55,
        websiteUrl: "https://www.precisionheatingair.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 20,
        name: "Salt Service Co. Plumbing, Air & Electric",
        address: "5900 Balcones Dr Ste 4000, Austin, TX 78731",
        googleRating: 4.9, reviewCount: 1420, recentReviewPct: 0.50,
        packPosition: 20, keywordRankAvg: 33.0,
        pageSpeed: 65, auditScore: 62, mobileScore: 60,
        websiteUrl: "https://www.saltserviceco.com",
        dataSource: "Sample data — Orbital top-9 by reviews · est. 2019",
        dataSourceUrl: "https://birdeye.com",
      },
    ],
  },


  /* ── Austin · Electricians ─────────────────────────────────── */
  'austin-electricians': {
    label: 'Electricians',
    city: 'Austin, TX',
    category: 'Electricians',
    businesses: [
      {
        id: 1,
        name: "Mr. Electric of Austin",
        address: "9901 Brodie Ln Ste 160, Austin, TX 78748",
        googleRating: 4.7, reviewCount: 1853, recentReviewPct: 0.40,
        packPosition: 1, keywordRankAvg: 1.8,
        pageSpeed: 72, auditScore: 74, mobileScore: 70,
        websiteUrl: "https://mrelectric.com/austin",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 2,
        name: "Tanner Electric",
        address: "1901 E 51st St Ste C, Austin, TX 78723",
        googleRating: 4.9, reviewCount: 312, recentReviewPct: 0.60,
        packPosition: 2, keywordRankAvg: 4.2,
        pageSpeed: 58, auditScore: 55, mobileScore: 52,
        websiteUrl: "https://www.tannerelectric.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 3,
        name: "Mister Sparky Electric",
        address: "4301 W William Cannon Dr Ste B, Austin, TX 78749",
        googleRating: 4.6, reviewCount: 978, recentReviewPct: 0.35,
        packPosition: 3, keywordRankAvg: 6.0,
        pageSpeed: 78, auditScore: 80, mobileScore: 76,
        websiteUrl: "https://www.mistersparky.com/austin",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 4,
        name: "Stan's Heating, Air, Plumbing & Electrical",
        address: "6016 Dillard Cir, Austin, TX 78752",
        googleRating: 4.7, reviewCount: 6791, recentReviewPct: 0.20,
        packPosition: 4, keywordRankAvg: 8.3,
        pageSpeed: 58, auditScore: 61, mobileScore: 55,
        websiteUrl: "https://www.stansac.com",
        dataSource: "Sample data — pending live pull",
      },

      {
        id: 5,
        name: "Triangle Electric Austin",
        address: "3101 Bee Cave Rd Ste 301, Austin, TX 78746",
        googleRating: 4.8, reviewCount: 224, recentReviewPct: 0.55,
        packPosition: 5, keywordRankAvg: 10.7,
        pageSpeed: 48, auditScore: 44, mobileScore: 46,
        websiteUrl: "https://www.triangleelectricaustin.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 6,
        name: "Abacus Plumbing, AC & Electrical",
        address: "2106 Denton Dr, Austin, TX 78758",
        googleRating: 4.6, reviewCount: 578, recentReviewPct: 0.35,
        packPosition: 6, keywordRankAvg: 13.2,
        pageSpeed: 66, auditScore: 70, mobileScore: 64,
        websiteUrl: "https://www.abacusplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 7,
        name: "ElectricMasters Austin",
        address: "7500 Rialto Blvd Ste 250, Austin, TX 78735",
        googleRating: 4.5, reviewCount: 187, recentReviewPct: 0.48,
        packPosition: 7, keywordRankAvg: 16.0,
        pageSpeed: 52, auditScore: 48, mobileScore: 50,
        websiteUrl: "https://www.electricmastersaustin.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 8,
        name: "Malco Electric",
        address: "10908 W Hwy 290, Austin, TX 78736",
        googleRating: 4.8, reviewCount: 425, recentReviewPct: 0.42,
        packPosition: 8, keywordRankAvg: 17.5,
        pageSpeed: 60, auditScore: 62, mobileScore: 58,
        websiteUrl: "https://www.malcoelectric.com",
        dataSource: "Sample data — licensed since 1983 · Angi featured",
        dataSourceUrl: "https://www.angi.com",
      },

      {
        id: 9,
        name: "AC Electric LLC",
        address: "4408 Gaines Ranch Loop, Austin, TX 78735",
        googleRating: 4.7, reviewCount: 356, recentReviewPct: 0.38,
        packPosition: 9, keywordRankAvg: 19.0,
        pageSpeed: 45, auditScore: 42, mobileScore: 43,
        websiteUrl: "https://www.acelectricaustin.com",
        dataSource: "Sample data — family-owned since 1984 · Expertise.com",
        dataSourceUrl: "https://www.expertise.com",
      },
      {
        id: 10,
        name: "ATX Electrical Services",
        address: "12301 Hymeadow Dr Ste 2A, Austin, TX 78750",
        googleRating: 5.0, reviewCount: 96, recentReviewPct: 0.72,
        packPosition: 10, keywordRankAvg: 20.5,
        pageSpeed: 55, auditScore: 50, mobileScore: 52,
        websiteUrl: "https://www.atxelectricalservices.com",
        dataSource: "Sample data — Birdeye 5.0★ 96 reviews",
        dataSourceUrl: "https://birdeye.com",
      },
      {
        id: 11,
        name: "Supersun Electrical Services",
        address: "8601 S Congress Ave Ste 106, Austin, TX 78745",
        googleRating: 4.9, reviewCount: 215, recentReviewPct: 0.62,
        packPosition: 11, keywordRankAvg: 22.0,
        pageSpeed: 50, auditScore: 47, mobileScore: 48,
        websiteUrl: "https://www.supersunelectrical.com",
        dataSource: "Sample data — Angi top-rated · SPAN panel specialist",
        dataSourceUrl: "https://www.angi.com",
      },
      {
        id: 12,
        name: "EMPWR Electric",
        address: "2401 E 6th St Ste 1008, Austin, TX 78702",
        googleRating: 4.9, reviewCount: 142, recentReviewPct: 0.68,
        packPosition: 12, keywordRankAvg: 23.5,
        pageSpeed: 62, auditScore: 58, mobileScore: 60,
        websiteUrl: "https://www.empwrelectric.com",
        dataSource: "Sample data — HomeAdvisor featured · est. 2020",
        dataSourceUrl: "https://www.homeadvisor.com",
      },

      {
        id: 13,
        name: "Austin Electric Company",
        address: "5555 N Lamar Blvd Ste K109, Austin, TX 78751",
        googleRating: 4.6, reviewCount: 485, recentReviewPct: 0.34,
        packPosition: 13, keywordRankAvg: 25.0,
        pageSpeed: 68, auditScore: 65, mobileScore: 63,
        websiteUrl: "https://www.austinelectriccompany.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 14,
        name: "Capitol Electric Texas",
        address: "3700 N Hills Dr Ste A, Austin, TX 78731",
        googleRating: 4.7, reviewCount: 298, recentReviewPct: 0.45,
        packPosition: 14, keywordRankAvg: 26.5,
        pageSpeed: 55, auditScore: 52, mobileScore: 50,
        websiteUrl: "https://www.capitolelectrictx.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 15,
        name: "Auspex Electrical",
        address: "9600 Escarpment Blvd Ste 745, Austin, TX 78749",
        googleRating: 4.8, reviewCount: 178, recentReviewPct: 0.58,
        packPosition: 15, keywordRankAvg: 28.0,
        pageSpeed: 48, auditScore: 45, mobileScore: 46,
        websiteUrl: "https://www.auspexelectrical.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 16,
        name: "Heritage Electric Austin",
        address: "1100 W 6th St Ste 201, Austin, TX 78703",
        googleRating: 4.5, reviewCount: 410, recentReviewPct: 0.30,
        packPosition: 16, keywordRankAvg: 29.5,
        pageSpeed: 62, auditScore: 60, mobileScore: 58,
        websiteUrl: "https://www.heritageelectricaustin.com",
        dataSource: "Sample data — pending live pull",
      },

      {
        id: 17,
        name: "Lone Star Electric",
        address: "4210 S Industrial Dr Ste 600, Austin, TX 78744",
        googleRating: 4.6, reviewCount: 265, recentReviewPct: 0.40,
        packPosition: 17, keywordRankAvg: 31.0,
        pageSpeed: 58, auditScore: 55, mobileScore: 54,
        websiteUrl: "https://www.lonestarelectricaustin.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 18,
        name: "Benchmark Electrical Solutions",
        address: "7801 N Lamar Blvd Ste D200, Austin, TX 78752",
        googleRating: 4.9, reviewCount: 88, recentReviewPct: 0.70,
        packPosition: 18, keywordRankAvg: 32.5,
        pageSpeed: 42, auditScore: 40, mobileScore: 41,
        websiteUrl: "https://www.benchmarkelectrical.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 19,
        name: "Fox Service Company — Electrical",
        address: "1506 Ferguson Ln Ste 102, Austin, TX 78754",
        googleRating: 4.8, reviewCount: 5127, recentReviewPct: 0.22,
        packPosition: 19, keywordRankAvg: 34.0,
        pageSpeed: 63, auditScore: 66, mobileScore: 59,
        websiteUrl: "https://www.foxservice.com",
        dataSource: "Sample data — Birdeye 6,094 cross-platform · est. 1972",
        dataSourceUrl: "https://birdeye.com",
      },
      {
        id: 20,
        name: "Daniel's Plumbing and Air — Electrical",
        address: "2929 Longhorn Blvd #105, Austin, TX 78758",
        googleRating: 4.7, reviewCount: 2772, recentReviewPct: 0.42,
        packPosition: 20, keywordRankAvg: 35.5,
        pageSpeed: 74, auditScore: 76, mobileScore: 72,
        websiteUrl: "https://www.danielsaustin.com",
        dataSource: "Sample data — ServiceAgent 2,772 Google reviews",
        dataSourceUrl: "https://www.serviceagent.com",
      },
    ],
  },


  /* ── Chicago · Plumbers ────────────────────────────────────── */
  'chicago-plumbers': {
    label: 'Plumbers',
    city: 'Chicago, IL',
    category: 'Plumbers',
    businesses: [
      {
        id: 1,
        name: "Rescue Plumbing",
        address: "1137 W Webster Ave, Chicago, IL 60614",
        googleRating: 4.9, reviewCount: 1534, recentReviewPct: 0.55,
        packPosition: 1, keywordRankAvg: 2.0,
        pageSpeed: 70, auditScore: 72, mobileScore: 68,
        websiteUrl: "https://www.myrescueplumbing.com",
        dataSource: "4.9★ Google · 1,534 reviews · multiple Chicago GBP listings · est. 2018",
        dataSourceUrl: "https://www.google.com/maps",
      },
      {
        id: 2,
        name: "J. Blanton Plumbing",
        address: "5765 N Lincoln Ave, Chicago, IL 60659",
        googleRating: 4.8, reviewCount: 2210, recentReviewPct: 0.45,
        packPosition: 2, keywordRankAvg: 3.5,
        pageSpeed: 65, auditScore: 68, mobileScore: 62,
        websiteUrl: "https://www.jblantonplumbing.com",
        dataSource: "Sample data — 30+ years experience · 5-star reviews",
      },
      {
        id: 3,
        name: "Four Seasons Plumbing & Sewer",
        address: "5701 W 73rd St, Chicago, IL 60638",
        googleRating: 4.6, reviewCount: 4520, recentReviewPct: 0.28,
        packPosition: 3, keywordRankAvg: 4.8,
        pageSpeed: 72, auditScore: 74, mobileScore: 70,
        websiteUrl: "https://www.fourseasonsheatingcooling.com",
        dataSource: "Sample data — Chicagoland's largest · est. 1971",
      },

      {
        id: 4,
        name: "Apex Plumbing & Sewer, Inc.",
        address: "4000 W Montrose Ave, Chicago, IL 60641",
        googleRating: 4.7, reviewCount: 890, recentReviewPct: 0.38,
        packPosition: 4, keywordRankAvg: 6.5,
        pageSpeed: 55, auditScore: 52, mobileScore: 50,
        websiteUrl: "https://www.apexplumbingchicago.com",
        dataSource: "Sample data — Expertise.com featured · est. 1984",
        dataSourceUrl: "https://www.expertise.com",
      },
      {
        id: 5,
        name: "Roto-Rooter Chicago",
        address: "4060 N Cicero Ave, Chicago, IL 60641",
        googleRating: 4.5, reviewCount: 3150, recentReviewPct: 0.25,
        packPosition: 5, keywordRankAvg: 8.0,
        pageSpeed: 68, auditScore: 70, mobileScore: 66,
        websiteUrl: "https://www.rotorooter.com/chicago/",
        dataSource: "Sample data — largest US plumbing provider · est. 1935",
      },
      {
        id: 6,
        name: "Rocket Plumbing Chicago",
        address: "1153 N Western Ave, Chicago, IL 60622",
        googleRating: 4.8, reviewCount: 645, recentReviewPct: 0.50,
        packPosition: 6, keywordRankAvg: 10.2,
        pageSpeed: 60, auditScore: 58, mobileScore: 56,
        websiteUrl: "https://www.rocketplumbing.com/chicago",
        dataSource: "Sample data — 24/7 emergency service",
      },
      {
        id: 7,
        name: "BMW Plumbing Inc.",
        address: "1775 W Diversey Pkwy, Chicago, IL 60614",
        googleRating: 4.9, reviewCount: 520, recentReviewPct: 0.52,
        packPosition: 7, keywordRankAvg: 12.5,
        pageSpeed: 48, auditScore: 45, mobileScore: 46,
        websiteUrl: "https://www.bmwplumbing.com",
        dataSource: "Sample data — family-owned · Angi Super Service",
        dataSourceUrl: "https://www.angi.com",
      },

      {
        id: 8,
        name: "Plumbing Experts Inc.",
        address: "3322 N Halsted St, Chicago, IL 60657",
        googleRating: 4.7, reviewCount: 412, recentReviewPct: 0.44,
        packPosition: 8, keywordRankAvg: 14.0,
        pageSpeed: 52, auditScore: 50, mobileScore: 48,
        websiteUrl: "https://www.plumbingexpertsinc.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 9,
        name: "All Rooter Plumbing",
        address: "2856 S Lowe Ave, Chicago, IL 60616",
        googleRating: 4.8, reviewCount: 375, recentReviewPct: 0.48,
        packPosition: 9, keywordRankAvg: 15.8,
        pageSpeed: 44, auditScore: 42, mobileScore: 40,
        websiteUrl: "https://www.allrooterplumbing.com",
        dataSource: "Sample data — BestProsInTown featured",
        dataSourceUrl: "https://bestprosintown.com",
      },
      {
        id: 10,
        name: "Chicago Plumbing Experts",
        address: "1930 N Clybourn Ave Ste 200, Chicago, IL 60614",
        googleRating: 4.6, reviewCount: 298, recentReviewPct: 0.42,
        packPosition: 10, keywordRankAvg: 17.5,
        pageSpeed: 62, auditScore: 60, mobileScore: 58,
        websiteUrl: "https://www.chicagoplumbingexperts.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 11,
        name: "Jiffy Plumbing & Heating",
        address: "4707 N Broadway, Chicago, IL 60640",
        googleRating: 4.7, reviewCount: 560, recentReviewPct: 0.35,
        packPosition: 11, keywordRankAvg: 19.0,
        pageSpeed: 50, auditScore: 48, mobileScore: 47,
        websiteUrl: "https://www.jiffyplumbing.com",
        dataSource: "Sample data — serving Chicagoland since 1989",
      },

      {
        id: 12,
        name: "Althoff Industries",
        address: "225 W Wacker Dr Ste 1550, Chicago, IL 60606",
        googleRating: 4.6, reviewCount: 1875, recentReviewPct: 0.30,
        packPosition: 12, keywordRankAvg: 20.5,
        pageSpeed: 66, auditScore: 64, mobileScore: 62,
        websiteUrl: "https://www.althoffindustries.com",
        dataSource: "Sample data — BestPickReports · est. 1928",
        dataSourceUrl: "https://bestpickreports.com",
      },
      {
        id: 13,
        name: "Dugan's Plumbing & Sewer",
        address: "6912 N Clark St, Chicago, IL 60626",
        googleRating: 4.8, reviewCount: 310, recentReviewPct: 0.55,
        packPosition: 13, keywordRankAvg: 22.0,
        pageSpeed: 42, auditScore: 40, mobileScore: 38,
        websiteUrl: "https://www.dugansplumbing.com",
        dataSource: "Sample data — family-owned · north side specialist",
      },
      {
        id: 14,
        name: "Brown Plumbing & Heating",
        address: "4241 W Irving Park Rd, Chicago, IL 60641",
        googleRating: 4.5, reviewCount: 245, recentReviewPct: 0.32,
        packPosition: 14, keywordRankAvg: 23.5,
        pageSpeed: 46, auditScore: 44, mobileScore: 42,
        websiteUrl: "https://www.brownplumbingchicago.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 15,
        name: "LaCassa Plumbing",
        address: "3500 N Pulaski Rd, Chicago, IL 60641",
        googleRating: 4.9, reviewCount: 180, recentReviewPct: 0.62,
        packPosition: 15, keywordRankAvg: 25.0,
        pageSpeed: 38, auditScore: 35, mobileScore: 36,
        websiteUrl: "https://www.lacassaplumbing.com",
        dataSource: "Sample data — Thumbtack top pro",
        dataSourceUrl: "https://www.thumbtack.com",
      },

      {
        id: 16,
        name: "Mr. Rooter Plumbing of Chicago",
        address: "5100 W Roosevelt Rd, Chicago, IL 60644",
        googleRating: 4.6, reviewCount: 720, recentReviewPct: 0.33,
        packPosition: 16, keywordRankAvg: 26.5,
        pageSpeed: 70, auditScore: 68, mobileScore: 66,
        websiteUrl: "https://www.mrrooter.com/chicago/",
        dataSource: "Sample data — national franchise · Neighborly brand",
        dataSourceUrl: "https://www.neighborly.com",
      },
      {
        id: 17,
        name: "North Shore Plumbing",
        address: "6455 N California Ave, Chicago, IL 60645",
        googleRating: 4.7, reviewCount: 155, recentReviewPct: 0.50,
        packPosition: 17, keywordRankAvg: 28.0,
        pageSpeed: 44, auditScore: 41, mobileScore: 40,
        websiteUrl: "https://www.northshoreplumbingchicago.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 18,
        name: "Baryenbruch Plumbing",
        address: "2900 W Belmont Ave, Chicago, IL 60618",
        googleRating: 4.8, reviewCount: 265, recentReviewPct: 0.46,
        packPosition: 18, keywordRankAvg: 29.5,
        pageSpeed: 40, auditScore: 38, mobileScore: 36,
        websiteUrl: "https://www.baryenbruchplumbing.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 19,
        name: "Citywide Plumbing & Sewer",
        address: "1844 N Damen Ave, Chicago, IL 60647",
        googleRating: 4.5, reviewCount: 410, recentReviewPct: 0.36,
        packPosition: 19, keywordRankAvg: 31.0,
        pageSpeed: 56, auditScore: 54, mobileScore: 52,
        websiteUrl: "https://www.citywideplumbingchicago.com",
        dataSource: "Sample data — pending live pull",
      },
      {
        id: 20,
        name: "Superior Plumbing & Drain",
        address: "3030 N Lincoln Ave, Chicago, IL 60657",
        googleRating: 4.7, reviewCount: 195, recentReviewPct: 0.58,
        packPosition: 20, keywordRankAvg: 32.5,
        pageSpeed: 52, auditScore: 50, mobileScore: 48,
        websiteUrl: "https://www.superiorplumbingdrain.com",
        dataSource: "Sample data — pending live pull",
      },
    ],
  },

};

// Default dataset key
const DEFAULT_DATASET = 'austin-plumbers';

// Backward-compat alias used by index.html preview
const RAW_BUSINESSES = DATASETS[DEFAULT_DATASET].businesses;
