// All datasets — add new cities/categories here
// Each entry: { label, city, category, businesses: [...] }

const DATASETS = {

  /* ── Austin · Plumbers ─────────────────────────────────────── */
  'austin-plumbers': {
    label: 'Plumbers',
    city: 'Austin, TX',
    category: 'Plumbers',
    sampleData: false,
    businesses: [
      {
        id: 1,
        name: "Radiant Plumbing & Air Conditioning",
        address: "901 Reinli St, Austin, TX 78751",
        googleRating: 4.8, reviewCount: 12426, recentReviewPct: 0.18,
        packPosition: 1, keywordRankAvg: 1.5,
        pageSpeed: 72, auditScore: 75, mobileScore: 68,
        websiteUrl: "https://radiantplumbing.com",
        dataSource: "ThreeBestRated #1 · Birdeye 12,426 reviews",
      },
      {
        id: 2,
        name: "Rooter-Man Plumbing Austin",
        address: "15503 Patricia St, Austin, TX 78728",
        googleRating: 4.9, reviewCount: 705, recentReviewPct: 0.45,
        packPosition: 2, keywordRankAvg: 3.2,
        pageSpeed: 52, auditScore: 58, mobileScore: 50,
        websiteUrl: "https://www.rooterman.com/greater-austin/",
        dataSource: "TrustAnalytica · Birdeye 1,202 cross-platform",
      },
      {
        id: 3,
        name: "Reliant Plumbing",
        address: "8740 N Lamar Blvd #203A, Austin, TX 78753",
        googleRating: 4.9, reviewCount: 784, recentReviewPct: 0.48,
        packPosition: 3, keywordRankAvg: 4.8,
        pageSpeed: 68, auditScore: 72, mobileScore: 65,
        websiteUrl: "https://reliantplumbing.com",
        dataSource: "ThreeBestRated #3 · TrustAnalytica 784 reviews",
      },
      {
        id: 4,
        name: "Proven Plumbing & Air",
        address: "300 Brushy Creek Rd Ste 402, Cedar Park, TX 78613",
        googleRating: 4.9, reviewCount: 2798, recentReviewPct: 0.40,
        packPosition: 4, keywordRankAvg: 7.1,
        pageSpeed: 71, auditScore: 74, mobileScore: 70,
        websiteUrl: "https://www.callproven.com",
        dataSource: "ServiceAgent · Birdeye 2,798 Google reviews",
      },

      {
        id: 5,
        name: "ABC Home & Commercial Services",
        address: "9475 US-290, Austin, TX 78724",
        googleRating: 4.9, reviewCount: 979, recentReviewPct: 0.30,
        packPosition: 5, keywordRankAvg: 8.5,
        pageSpeed: 65, auditScore: 68, mobileScore: 60,
        websiteUrl: "https://www.abchomeandcommercial.com/austin/plumbing",
        dataSource: "ConsumerAffairs · Birdeye 1,128 reviews · est. 1949",
      },
      {
        id: 6,
        name: "Daniel's Plumbing and Air Conditioning",
        address: "2929 Longhorn Blvd #105, Austin, TX 78758",
        googleRating: 4.7, reviewCount: 2772, recentReviewPct: 0.42,
        packPosition: 6, keywordRankAvg: 10.2,
        pageSpeed: 74, auditScore: 76, mobileScore: 72,
        websiteUrl: "https://www.danielsaustin.com",
        dataSource: "ServiceAgent · Homespothq 2,772 Google reviews",
      },
      {
        id: 7,
        name: "Fox Service Company",
        address: "1506 Ferguson Ln Ste 102, Austin, TX 78754",
        googleRating: 4.8, reviewCount: 5127, recentReviewPct: 0.22,
        packPosition: 7, keywordRankAvg: 11.8,
        pageSpeed: 63, auditScore: 66, mobileScore: 59,
        websiteUrl: "https://www.foxservice.com",
        dataSource: "Birdeye 6,094 cross-platform · est. 1972",
      },
      {
        id: 8,
        name: "Stan's Heating, Air, Plumbing & Electrical",
        address: "6016 Dillard Cir, Austin, TX 78752",
        googleRating: 4.7, reviewCount: 6791, recentReviewPct: 0.20,
        packPosition: 8, keywordRankAvg: 13.2,
        pageSpeed: 58, auditScore: 61, mobileScore: 55,
        websiteUrl: "https://www.stansac.com",
        dataSource: "Birdeye 6,791 Google · 573 Yelp · est. 1954",
      },

      {
        id: 9,
        name: "Abacus Plumbing, AC & Electrical",
        address: "2106 Denton Dr, Austin, TX 78758",
        googleRating: 4.6, reviewCount: 578, recentReviewPct: 0.35,
        packPosition: 9, keywordRankAvg: 15.5,
        pageSpeed: 66, auditScore: 70, mobileScore: 64,
        websiteUrl: "https://www.abacusplumbing.com",
        dataSource: "Best Pick Reports 4.6★ · 578 Google reviews · est. 2003",
      },
      {
        id: 10,
        name: "S&D Plumbing",
        address: "3432 Greystone Dr Ste 112, Austin, TX 78731",
        googleRating: 4.7, reviewCount: 816, recentReviewPct: 0.38,
        packPosition: 10, keywordRankAvg: 17.3,
        pageSpeed: 61, auditScore: 64, mobileScore: 58,
        websiteUrl: "https://www.sanddplumbing.com",
        dataSource: "Birdeye 816 Google · family-owned est. 1980",
      },
      {
        id: 11,
        name: "Moore & More Plumbing",
        address: "1816 Bissel Ln, Austin, TX 78745",
        googleRating: 4.8, reviewCount: 266, recentReviewPct: 0.50,
        packPosition: 11, keywordRankAvg: 19.0,
        pageSpeed: 55, auditScore: 52, mobileScore: 50,
        websiteUrl: "https://www.mooremoreplumbing.com",
        dataSource: "Birdeye 338 cross-platform · est. 1986",
      },
      {
        id: 12,
        name: "EZ Flow Plumbing",
        address: "1914 W Howard Ln Ste J, Austin, TX 78728",
        googleRating: 4.9, reviewCount: 54, recentReviewPct: 0.65,
        packPosition: 12, keywordRankAvg: 22.0,
        pageSpeed: 48, auditScore: 44, mobileScore: 45,
        websiteUrl: "https://ezflowplumbingtexas.com",
        dataSource: "4.9★ Google · 276 Yelp reviews · est. 2009",
      },

      {
        id: 13,
        name: "Excalibur Plumbing",
        address: "11880 Hero Way W Ste 308, Leander, TX 78641",
        googleRating: 4.7, reviewCount: 501, recentReviewPct: 0.40,
        packPosition: 13, keywordRankAvg: 23.5,
        pageSpeed: 70, auditScore: 72, mobileScore: 68,
        websiteUrl: "https://www.excaliburplumbing.com",
        dataSource: "Birdeye 501 Google · Angi 92% approval",
      },
      {
        id: 14,
        name: "Economy Plumbing Services",
        address: "701 Tillery St Ste 12, Austin, TX 78702",
        googleRating: 4.6, reviewCount: 586, recentReviewPct: 0.35,
        packPosition: 14, keywordRankAvg: 25.0,
        pageSpeed: 52, auditScore: 48, mobileScore: 50,
        websiteUrl: "https://www.plumbersthatcare.com",
        dataSource: "ServiceAgent 586 Google · Birdeye 642 reviews · est. 2012",
      },
      {
        id: 15,
        name: "Roto-Rooter Plumbing & Water Cleanup",
        address: "2324 Ridgepoint Dr Ste A, Austin, TX 78754",
        googleRating: 4.6, reviewCount: 400, recentReviewPct: 0.30,
        packPosition: 15, keywordRankAvg: 26.5,
        pageSpeed: 60, auditScore: 62, mobileScore: 58,
        websiteUrl: "https://www.rotorooter.com/austin/",
        dataSource: "ThreeBestRated top-3 · TrustAnalytica 4.6★ · 302 Yelp",
      },
      {
        id: 16,
        name: "Redbud Plumbing",
        address: "9705 Burnet Rd Ste 605, Austin, TX 78758",
        googleRating: 4.9, reviewCount: 75, recentReviewPct: 0.70,
        packPosition: 16, keywordRankAvg: 28.0,
        pageSpeed: 72, auditScore: 68, mobileScore: 70,
        websiteUrl: "https://redbudplumbing.com",
        dataSource: "Angi 5.0★ · BuildZoom top 11% TX contractors",
      },

      {
        id: 17,
        name: "Clarke Kent Plumbing",
        address: "1408 W Ben White Blvd, Austin, TX 78704",
        googleRating: 4.4, reviewCount: 485, recentReviewPct: 0.28,
        packPosition: 17, keywordRankAvg: 29.5,
        pageSpeed: 45, auditScore: 41, mobileScore: 43,
        websiteUrl: "https://www.clarkekentplumbing.com",
        dataSource: "TrustAnalytica 4.4★ · 210 Yelp reviews · est. 1986",
      },
      {
        id: 18,
        name: "Wilson Plumbing Company",
        address: "906 E 47th St, Austin, TX 78751",
        googleRating: 4.8, reviewCount: 40, recentReviewPct: 0.40,
        packPosition: 18, keywordRankAvg: 31.0,
        pageSpeed: 38, auditScore: 35, mobileScore: 36,
        websiteUrl: "https://www.wilsonplumbingaustin.com",
        dataSource: "Angi 4.9★ · Super Service Awards 2011-2017 · est. 1947",
      },
      {
        id: 19,
        name: "Accurate Plumbing Solutions",
        address: "5234 Balcones Dr, Austin, TX 78731",
        googleRating: 4.8, reviewCount: 342, recentReviewPct: 0.52,
        packPosition: 19, keywordRankAvg: 32.0,
        pageSpeed: 55, auditScore: 58, mobileScore: 52,
        websiteUrl: "https://www.accurateplumbingaustin.com",
        dataSource: "BestProsInTown featured · est. 2010",
      },
      {
        id: 20,
        name: "Altruistic Plumbing",
        address: "7800 Shoal Creek Blvd Ste 265, Austin, TX 78757",
        googleRating: 4.9, reviewCount: 189, recentReviewPct: 0.62,
        packPosition: 20, keywordRankAvg: 33.5,
        pageSpeed: 60, auditScore: 55, mobileScore: 57,
        websiteUrl: "https://www.altruisticplumbing.com",
        dataSource: "Thumbtack top pro · est. 2017",
      },
    ],
  },

};

// Default dataset key
const DEFAULT_DATASET = 'austin-plumbers';

// Backward-compat alias used by index.html preview
const RAW_BUSINESSES = DATASETS[DEFAULT_DATASET].businesses;
